# **PROJECT**
- Explore the financial data
- Develop a financial dashboard with `dash` library
- Try using different visualizations

In [5]:
import yfinance as yf

In [6]:
apple = yf.Ticker('AAPL')
apple.history(period='5y')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2020-10-19 00:00:00-04:00,116.687216,117.134665,112.504534,112.815804,120639300,0.0,0.0
2020-10-20 00:00:00-04:00,113.029804,115.733966,112.475355,114.304070,124423700,0.0,0.0
2020-10-21 00:00:00-04:00,113.487001,115.471347,113.273002,113.681549,89946000,0.0,0.0
2020-10-22 00:00:00-04:00,114.245712,114.819619,111.463738,112.592094,101988000,0.0,0.0
2020-10-23 00:00:00-04:00,113.214619,113.370257,111.162184,111.901451,82572600,0.0,0.0
...,...,...,...,...,...,...,...
2025-10-13 00:00:00-04:00,249.380005,249.690002,245.559998,247.660004,38142900,0.0,0.0
2025-10-14 00:00:00-04:00,246.600006,248.850006,244.699997,247.770004,35478000,0.0,0.0
2025-10-15 00:00:00-04:00,249.490005,251.820007,247.470001,249.339996,33893600,0.0,0.0
2025-10-16 00:00:00-04:00,248.250000,249.039993,245.130005,247.449997,39698000,0.0,0.0
2025-10-17 00:00:00-04:00,248.020004,251.360001,247.270004,250.898193,24826485,0.0,0.0

In [7]:
income_statement = apple.financials
balance_sheet = apple.balance_sheet
cash_flow = apple.cash_flow
dividends = apple.dividends
income_statement

,2024-09-30,2023-09-30,2022-09-30,2021-09-30
Tax Effect Of Unusual Items,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Tax Rate For Calcs,2.410000e-01,1.470000e-01,1.620000e-01,1.330000e-01
Normalized EBITDA,1.346610e+11,1.258200e+11,1.305410e+11,1.231360e+11
Net Income From Continuing Operation Net Minority Interest,9.373600e+10,9.699500e+10,9.980300e+10,9.468000e+10
Reconciled Depreciation,1.144500e+10,1.151900e+10,1.110400e+10,1.128400e+10
Reconciled Cost Of Revenue,2.103520e+11,2.141370e+11,2.235460e+11,2.129810e+11
EBITDA,1.346610e+11,1.258200e+11,1.305410e+11,1.231360e+11
EBIT,1.232160e+11,1.143010e+11,1.194370e+11,1.118520e+11
Net Interest Income,NaN,-1.830000e+08,-1.060000e+08,1.980000e+08
Interest Expense,NaN,3.933000e+09,2.931000e+09,2.645000e+09
Interest Income,NaN,3.750000e+09,2.825000e+09,2.843000e+09
Normalized Income,9.373600e+10,9.699500e+10,9.980300e+10,9.468000e+10
Net Income From Continuing And Discontinued Operation,9.373600e+10,9.699500e+10,9.980300e+10,9.468000e+10
Total Expenses,2.678190e+11,2.689840e+11,2.748910e+11,2.568680e+11
Total Operating Income As Reported,1.232160e+11,1.143010e+11,1.194370e+11,1.089490e+11
Diluted Average Shares,1.540810e+10,1.581255e+10,1.632582e+10,1.686492e+10
Basic Average Shares,1.534378e+10,1.574423e+10,1.621596e+10,1.670127e+10
Diluted EPS,6.080000e+00,6.130000e+00,6.110000e+00,5.610000e+00
Basic EPS,6.110000e+00,6.160000e+00,6.150000e+00,5.670000e+00
Diluted NI Availto Com Stockholders,9.373600e+10,9.699500e+10,9.980300e+10,9.468000e+10
Net Income Common Stockholders,9.373600e+10,9.699500e+10,9.980300e+10,9.468000e+10
Net Income,9.373600e+10,9.699500e+10,9.980300e+10,9.468000e+10
Net Income Including Noncontrolling Interests,9.373600e+10,9.699500e+10,9.980300e+10,9.468000e+10
Net Income Continuous Operations,9.373600e+10,9.699500e+10,9.980300e+10,9.468000e+10
Tax Provision,2.974900e+10,1.674100e+10,1.930000e+10,1.452700e+10
Pretax Income,1.234850e+11,1.137360e+11,1.191030e+11,1.092070e+11
Other Income Expense,2.690000e+08,-5.650000e+08,-3.340000e+08,6.000000e+07
Other Non Operating Income Expenses,2.690000e+08,-5.650000e+08,-3.340000e+08,6.000000e+07
Net Non Operating Interest Income Expense,NaN,-1.830000e+08,-1.060000e+08,1.980000e+08
Interest Expense Non Operating,NaN,3.933000e+09,2.931000e+09,2.645000e+09
Interest Income Non Operating,NaN,3.750000e+09,2.825000e+09,2.843000e+09
Operating Income,1.232160e+11,1.143010e+11,1.194370e+11,1.089490e+11
Operating Expense,5.746700e+10,5.484700e+10,5.134500e+10,4.388700e+10
Research And Development,3.137000e+10,2.991500e+10,2.625100e+10,2.191400e+10
Selling General And Administration,2.609700e+10,2.493200e+10,2.509400e+10,2.197300e+10
Gross Profit,1.806830e+11,1.691480e+11,1.707820e+11,1.528360e+11
Cost Of Revenue,2.103520e+11,2.141370e+11,2.235460e+11,2.129810e+11
Total Revenue,3.910350e+11,3.832850e+11,3.943280e+11,3.658170e+11
Operating Revenue,3.910350e+11,3.832850e+11,3.943280e+11,3.658170e+11